### ISSUE TITLE
search doesn't work due to "text score" not being available

### ISSUE THREAD

**Issue by dwatley** [barisusakli/nodebb-plugin-dbsearch#28]
I searched for this error and found a recent commit to MongoDB with the text string here: https://github.com/mongodb/mongo/commit/a8414a21ef6594b2e786652e4823687cd1b3ec72

I could be wrong but this seems to be due to a code change in MongoDB. Basically searching is completely non functional, though it does appear to be indexing according to the admin panel. Attempting to search from the sidebar produces an "Internal Error", and searching from the top bar near the notifications/chats returns no results.

#### Logs

> Jan 03 21:09:07 nodebb nodebb[13804]: 3/1 21:09:07 [24951] - error: [plugins] filter:search.query,  pipeline requires text score metadata, but there is no text score available
> Jan 03 21:09:07 nodebb nodebb[13804]: 3/1 21:09:07 [24951] - error: /api/search
> Jan 03 21:09:07 nodebb nodebb[13804]:  MongoError: pipeline requires text score metadata, but there is no text score available
> Jan 03 21:09:07 nodebb nodebb[13804]:     at Function.MongoError.create (/opt/nodebb/node_modules/mongodb-core/lib/error.js:31:11)
> Jan 03 21:09:07 nodebb nodebb[13804]:     at queryCallback (/opt/nodebb/node_modules/mongodb-core/lib/cursor.js:212:36)
> Jan 03 21:09:07 nodebb nodebb[13804]:     at /opt/nodebb/node_modules/mongodb-core/lib/connection/pool.js:455:18
> Jan 03 21:09:07 nodebb nodebb[13804]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
> Jan 03 21:09:07 nodebb nodebb[13804]:     at process._tickCallback (internal/process/next_tick.js:98:9)

#### Version Information
MongoDB version: `3.4.1`
NodeBB version: `1.4.2 (d5fb6dac38e4fb102dcd0a0256238019da1e84cf)`
nodebb-plugin-dbsearch version: `nodebb-plugin-dbsearch@1.0.4`

**Comment by dwatley** [comment]
Downgrading the MongoDB version to `3.2.11` per the [downgrade instructions](https://docs.mongodb.com/manual/release-notes/3.4-downgrade-standalone/) including:
1. setting feature compatibility level to `3.2`
1. re-indexing to `v: 1`
1. in the dbsearch plugin clearing the index and re-indexing.

Search now works as expected. So this seems to be an issue of compatibility with the new release of MongoDB.

**Comment by barisusakli** [comment]
Is this reproducible on a fresh install with mongodb 3.4.1?
