### ISSUE TITLE
Unable to load the template -- admin/plugins/dbsearch (Not Found)

### ISSUE THREAD

**Issue by brickcap** [barisusakli/nodebb-plugin-dbsearch#30]
* NodeBB version and git hash (to find your git hash, execute `git rev-parse HEAD` from the main NodeBB directory) -- v1.4.5 (d19e59f1e13f4a22eb44d5334b2a81d99e030b36)
* Database (mongo or redis) and it's version -- mongodb 3.4.3
* Exact steps to cause this issue
    1. I went to the admin panel and clicked on `plugins/dbsearch`
    2. I got no response from my current page so I looked into the console and noticed admin/plugins/dbsearch (Not Found) error

Here is the complete message:- 

```
Uncaught Error: Unable to load template: admin/plugins/dbsearch (Not Found)
    at Object.error (acp.min.js:11)
    at l (acp.min.js:1)
    at Object.fireWith [as rejectWith] (acp.min.js:1)
    at E (acp.min.js:3)
    at XMLHttpRequest.<anonymous> (acp.min.js:3)

```   
* What you expected
    * I expected to open the dbsearch interface where I could configure the search settings for my app
* What happened instead
    * Nothing happened.... nothing at all.....

**Comment by julianlam** [comment]
Did you run ./nodebb build?

**Comment by brickcap** [comment]
I hadn't. But I did now and the problem is fixed. Thanks a lot!
