### ISSUE TITLE
The settings page can not be displayed

### ISSUE THREAD

**Issue by pczbq806** [barisusakli/nodebb-plugin-dbsearch#31]
I using NodeBB v1.4.6.
The browser does not show the new page after click [Elasticsearch](http://localhost:4567/admin/plugins/dbsearch), and then I refreshed the page, the browser displays such an error message:
```
/admin/plugins/dbsearch

Failed to lookup view "admin/plugins/dbsearch" in views directory "/Volumes/Home/NodeBB/build/public/templates"
```

**Comment by barisusakli** [comment]
Running ./nodebb build should fix this
