### ISSUE TITLE
Boolean operators support for searches

### ISSUE THREAD

**Issue by Hadden89** [barisusakli/nodebb-plugin-dbsearch#43]
Sometimes, it's hard to find content in NodeBB based forums due lack of the support of [these](https://libguides.mit.edu/c.php?g=175963&p=1158594). 
Often tag system and plain searches in the categories show a lot of results which are not precise.

Wondering if it could be easily implemented in some way.

**Comment by barisusakli** [comment]
and/or is supported in the advacned search panel, change `match words` from `all` to `any` if you want `OR`

MongoDB also supports not you can search for `"php" -"nodebb"` to match php but not nodebb

**Comment by An-dz** [comment]
> and/or is supported in the advacned search panel, change `match words` from `all` to `any` if you want `OR`

But that's only global `AND` and `OR`, from my point of view the request is to allow use of both.

E.g. `(computer AND bool) OR boolean`
