### ISSUE TITLE
Add ability to exclude categories from index

### ISSUE THREAD

**Issue by djensen47** [barisusakli/nodebb-plugin-dbsearch#45]
We have 1.2M posts indexed and on a 4GB Digital Ocean instance (NodeBB is on a separate instance), search is _very_ slow 20-30s for select searches like "USSR" others have fewer results and are much faster. If Mongo gets hammered with a long search a few too many times in a row, it crashes. I can keep upgrading the instance until the entire index can fit in memory but I'd rather spend money on redundancy rather than memory. I.e., it's rather not spend $120/month per instance for search.

As it turns out, a big portion of our 1.2M posts are "play by forum" games. Each player posts their turn assisted by other software. These _posts_ *do not* need to be indexed.

Our users would like to be able to search the topic titles however.

I would like to propose the ability to index (or exclude) select categories from the post index _and_ select categories from the topic index. 

In our case we only have 32k posts so I'd want all of them indexed but I definitely want to exclude 4-5 categories from the post index.

---

Here's out forum:
https://www.axisandallies.org/forums/

**Comment by djensen47** [comment]
Also, is there a workaround that I could have into place to make this work. (Sorry, I haven't dug into the code yet).

**Comment by djensen47** [comment]
It looks like we can use `partialFilterExpression` on the index creation.

**Comment by barisusakli** [comment]
Sounds like a good enchancement, you could possibly modify https://github.com/barisusakli/nodebb-plugin-dbsearch/blob/master/lib/dbsearch.js#L260 and check for `cid` and if it matches a certain excluded cid just return and not index until I implement this in the db search ACP itself.

**Comment by djensen47** [comment]
Sounds good, I'll add it to the to do list. 😁

**Comment by djensen47** [comment]
Awesome, thanks for doing this! Hopefully it will result in fewer mongodb crashes.

**Comment by barisusakli** [comment]
@djensen47 check out https://github.com/barisusakli/nodebb-plugin-dbsearch/issues/46 as well.

It removes the `id` index and uses mongodbs _id index instead, it shoud reduce index size a bit more.
