### ISSUE TITLE
I can't upgrade to 3.0.0

### ISSUE THREAD

**Issue by djensen47** [barisusakli/nodebb-plugin-dbsearch#47]
I've tried to install 3.0.0

`npm install --save nodebb-plugin-dbsearch@3.0.0`

(I think I tried other stuff as well)

Then when I `./nodebb upgrade` it reverts the version to the old one. I thought I knew how to upgrade plugins but I guess not?

**Comment by barisusakli** [comment]
Core pins the version, upgrade core if you want the latest version of this plugin. https://github.com/NodeBB/NodeBB/blob/master/install/package.json#L83

**Comment by djensen47** [comment]
Okay, and core 1.11 is still under development so I'd have to run NodeBB from master, correct?

**Comment by barisusakli** [comment]
Yes, or wait for 1.11.0 to release which should be tomorrow
