### ISSUE TITLE
"Posted by" automatically trims

### ISSUE THREAD

**Issue by PatheticMustan** [barisusakli/nodebb-plugin-dbsearch#50]
Searching for the user "00100000" will search up for the posts by "00100000" but the next time you search, it will search for posts by "100000"

**Comment by PatheticMustan** [comment]
Before searching:
![f5b6a71f-c978-43fa-b239-8eb8b9e22172](https://user-images.githubusercontent.com/35382971/51988220-26f56980-2472-11e9-81dd-af90a2939a0c.png)

After searching:
![6e5097e4-612a-4bf4-ac4e-383a59e441a4](https://user-images.githubusercontent.com/35382971/51988219-26f56980-2472-11e9-8611-c6e37ce442f4.png)

**Comment by barisusakli** [comment]
Bug in core

**Comment by barisusakli** [comment]
@PatheticMustan fixed in core, thanks for reporting.
