### ISSUE TITLE
Quick Search widget links to wrong url

### ISSUE THREAD

**Issue by migoun** [barisusakli/nodebb-plugin-dbsearch#51]
Problem occurs if the forum is hosted unter a sub url: **localhost:4567/forum**
Instead of just *localhost:4567
While this search works normal and is expected behaviour:
![image](https://user-images.githubusercontent.com/6028796/54420012-31f61780-4709-11e9-9925-524f40197119.png)

returns posts to the right target: localhost:4567/**forum**/post/1234,

**The quick search returns results with wrong links:**
![image](https://user-images.githubusercontent.com/6028796/54420290-e728cf80-4709-11e9-89d8-8bd9952ca24c.png)

Links here are: localhost:4567/post/1234. No **forum** included in the link. So all the links here doesn't work.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7446
