### ISSUE TITLE
Randomly nothing will happen when you click on quick search

### ISSUE THREAD

**Issue by n-log-n** [barisusakli/nodebb-plugin-dbsearch#53]
Browser: Chrome version 74.0
Nodebb: v1.12.1

The clicks on quick search stop responding randomly before working again. If you search something in quick search box and from the dropdown click on a result item then, what appears to be very random, those clicks will simply close the search box and nothing will happen. The search results remains there and if you open the drop-down and click on the same item couple of times, it eventually works. Clicking on something else still works. 

I don't see any error in the developer's console either. 

Please, let me know if others have seen this behavior. If it is known or if you guys need additional information to re-produce. 

Other than this dbsearch plugin, we have embed, mention, write api plugins installed.

**Comment by fais3000** [comment]
@barisusakli This happens on Nodebb: v1.12.2 too, with no other custom plugins except DB search

**Comment by barisusakli** [comment]
I think this happens because this timeout is too small https://github.com/NodeBB/NodeBB/blob/master/public/src/app.js#L642.

I am going to increase it so it catches the click handlers.
