### ISSUE TITLE
Support Quill: Display html output instead of delta

### ISSUE THREAD

**Issue by PostMidnight** [barisusakli/nodebb-plugin-dbsearch#54]
Hi @barisusakli 
It may be that one of the hooks is not working properly, let me explain:
when I search, the output of the search is showing as json delta, while it should be displayed as html.
It might be that one of the hooks being used is returning delta while it should have returned html in this specific case.
I suspect its related to filter:post.getFields hook.
I might be wrong of course.
I hope you'll take a look. Thanks!
JJ.

**Comment by barisusakli** [comment]
This has nothing to do with db search plugin, I think you guys used `filter:post.getFields` hook to change .content into delta which will cause all plugins/core to return delta as content. Will have to use another hook to solve that original problem.

**Comment by julianlam** [comment]
@PostMidnight This may be related to the most recent commit where I updated `getPostFields` via plugin hook to return the delta instead of `content`.

**Comment by PostMidnight** [comment]
Hi @barisusakli and @julianlam 

Yes that's exactly right - the problem stems from filter:post.getFields getting triggered by search. This is what I noted before I posted the issue, and I verified that with a debugger.

Shall we just create a new hook? 

I just want to make sure the issue is on the return path. That is, that search is performed
on the actual post data and not on the quill delta ;)

For your reference this is the hook that gets triggered in quill:

```
{ "hook": "filter:post.getFields", "method": "appendDelta" }

plugin.appendDelta = async (data) => {
	if (!data.fields.includes('content')) {
		return data;
	}

	// For each pid, grab the quillDelta and replace content with it
	const deltas = await db.getObjectsFields(data.pids.map(pid => 'post:' + pid), ['quillDelta']);
	data.posts = data.posts.map((post, idx) => {
		if (deltas[idx]) {
			post.content = deltas[idx].quillDelta;
		}

		return post;
	});

	return data;
};

```

**Comment by julianlam** [comment]
Nevertheless, this isn't anything to do with dbsearch.

**Comment by PostMidnight** [comment]
OK, I'll transfer to quill.
