### ISSUE TITLE
lib/postrgres.js - bug

### ISSUE THREAD

**Issue by AlmasNurbayev** [barisusakli/nodebb-plugin-dbsearch#67]
in row 26 - extra comma. position 142

	await db.pool.query('CREATE TABLE IF NOT EXISTS "searchchat" ( "id" BIGINT NOT NULL PRIMARY KEY, "content" TEXT, "rid" BIGINT, "uid" BIGINT, )');

**Comment by barisusakli** [comment]
@AlmasNurbayev thanks for reporting, fixed in 6.2.1
