### ISSUE TITLE
is it fully compatible with v2?

### ISSUE THREAD

**Issue by k1r0s** [barisusakli/nodebb-plugin-dbsearch#69]
where I can check compatibility across noedbb versions?

As far as I can see this plugin has been pinpointed to be compatible with 1.19 and then directly to 3.0.0

https://github.com/barisusakli/nodebb-plugin-dbsearch/blame/master/package.json#L30

**Comment by julianlam** [comment]
As dbsearch is bundled with NodeBB you can just install the version indicated in install/package.json
