### ISSUE TITLE
Search Page not working in v0.6.x

### ISSUE THREAD

**Issue by drewdotpro** [barisusakli/nodebb-plugin-dbsearch#7]
Tried this out (is it the only search plugin?!) for v0.6.x and searches have an issue with broken templates I think?
https://i.imgur.com/XwMw3oz.jpg
You get no search results, and a broken page (as above)
As well as a console error in JS of "Uncaught TypeError: Cannot read property 'split' of undefined" but that's probably more a symptom of the template render issue.

**Comment by barisusakli** [comment]
Make sure your theme is up to date and templates.js module is also version 0.1.15.
